export const ADD_POST_SUCCESS = 'ADD_POST_SUCCESS'
export const START_ADD_POST = 'START_ADD_POST'
export const ADD_POST_FAIL = 'ADD_POST_FAIL'

export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS'
export const FETCH_POSTS_FAIL = 'FETCH_POSTS_FAIL'
export const FETCH_POSTS_START = 'FETCH_POSTS_START'